### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by nar53** [feren-OS/feren-OS-Bug-Reporting#10]
I've tried installing RC17 & 16.2 and get the same result with both, I can boot from the USB but installation fails when installing Grub. see image.

![feren-grub-fail](https://cloud.githubusercontent.com/assets/22550953/25294692/abb9790e-26e0-11e7-8053-0ec885c9689f.jpg)
Hope someone can help.

**Comment by scomnetgate** [comment]
You can disable UEFI and Secure Boot and Enable Legacy Boot in bios and try again to install the system.

**Comment by nar53** [comment]
Thanks for the info, worked perfectly. I'm so used to enabling UEFI these days it never occurred to me to disable it!

**Comment by scomnetgate** [comment]
Many try make us believe that the windows 10 way it's the only way...

**Comment by feren** [comment]
@nar53 Did you connect to WiFi?

**Comment by feren** [comment]
Possible duplicate of #5 if the user hadn't connected to internet before installing

**Comment by nar53** [comment]
I did connect to the net but not by WiFi. All went smoothly once I followed scomnetgate's suggestions.

**Comment by feren** [comment]
Oh ok, hmm, odd, that it isn't installing the package ok...

**Comment by feren** [comment]
This might be fixed in 2017.1, where the needed packages will now be stored in an ISO

**Comment by feren** [comment]
Because of this issue is mentioned in the Ubuntu 16.04 Release Notes, this has been marked as Upstream.
