### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by Hot-Chilli** [feren-OS/feren-OS-Bug-Reporting#11]
About the language/locales problem, which affects the Update Manager (with some specific languages), the Menu (any menu containing shortcuts to the folders within Home), and even the Settings Manager (though this seems to be solved in the RC, but it deserves to be double-checked) I suggest talking with our common friend. I told him something about this issue in Feren. In my opinion, the translations and/or some language-specific characters are missing.

**Comment by feren** [comment]
@raymerjacque Any advice on how to fix the locale bug?

**Comment by raymerjacque** [comment]
i had that issue twice. Once on a build a long time ago, i solved it by pre installing all the language packs. The other time i had it i changed language manager. i cant remember if i had mint local and change to gnome language or the other way around.

**Comment by Hot-Chilli** [comment]
It was Mint Language Manager and you change it to Gnome Language support, which is otherwise embedded in all the LinDoz versions since then. It works very well in its basic function and the locales anomalies are gone.
