### ISSUE TITLE
LiveCD Boots into TTY1

### ISSUE THREAD

**Issue by eaglewealth** [feren-OS/feren-OS-Bug-Reporting#13]
Hi

when I boot feren OS and it now in text asking for mint login. So what the login and password to use to be able to load Feren OS.  I cant bypass it. Using 2017.01 Feren.

"Linux Mint 18.1 Serena mint tty1"
"mint login: ????"

Thanks

**Comment by feren** [comment]
@eaglewealth 
Username: mint
Password: NOTHING

Hmm, looking at that though, did the ISO download correctly for you (Check MD5Sums) as that says the MDM Login Screen didn't start up.

Once you've logged into TTY, you'll be able to try and get a graphical session by running 'startx'

**Comment by feren** [comment]
Can you try feren OS Early Access to see if it also has the same problem?
http://ferenos.weebly.com/developer-center

**Comment by feren** [comment]
Since the issue reporter never commented back, this issue will be closed.
