### ISSUE TITLE
Feren OS on American Mega Trends Computer

### ISSUE THREAD

**Issue by gilbertstraight** [feren-OS/feren-OS-Bug-Reporting#14]
Using a 2.66 Ghz Processor core Duo, 4 Mbs. Ram with Hd Graphics. Feren OS took 58 minutes to Boot and would not use the themes and was acting really sluggish.Tried to install Feren OS with success as the install kept crashing.

**Comment by feren** [comment]
Is this bug present in Linux Mint 18.1?

**Comment by gilbertstraight** [comment]
Yes Sir it has to do with Feren OS I just got it checked it. The ISO checked out okay, but will not install on my Computer as I said.

**Comment by gilbertstraight** [comment]
Problem Has Been Solved. Feren OS is now Installed on the Computer and working as well as expected

**Comment by gilbertstraight** [comment]
The Issue is resolved Feren OS  Just took a Long time to install. 3 Hours 47 minutes

**Comment by gilbertstraight** [comment]
Feren OS is installed Next to Linux Mint KDE. It just took 3 hours 47 minutes to do but well worth the wait
