### ISSUE TITLE
Apps don't match categories in start menu

### ISSUE THREAD

**Issue by streety71** [feren-OS/feren-OS-Bug-Reporting#15]
Hi there - first of all congratulations for your fantastic job with this distro. After two days on feren-os I'm totally addicted to the stylishness and ease of use.
One thing that caught my eye though is a mismatch of the installed programs in the start-menu. In "Games" for an example there are GIMP, E-Book-Veiwer, Variety, Scribus and so on. The only thing I can't find in there is a game ...  Is there a possibility to sort the menu by myself?
![schreibtisch_001](https://cloud.githubusercontent.com/assets/28544436/25823593/ded2b648-343c-11e7-9417-c310760f7e72.jpg)

Im working on a Dell Precision T3500 in a German setup and had quite a hard time installing feren as I didn't suceed to boot from USB and the DVD took forever. But now it's done, I have to say, it was worth the while.

**Comment by feren** [comment]
@streety71 That's a glitch with the Slingshot menu, try restarting Cinnamon:
Ctrl+Alt+Esc, or Right-click on bottom-bar, Troubleshoot, Restart Cinnamon

**Comment by streety71** [comment]
Too late - I already installed the original Mint menu and I'm completely happy with it. The Slingshot icons were a bit too big for my taste.

**Comment by feren** [comment]
@streety71 There's Mint Menu already there as an option, alongside a fork of it called CinnVIIStarkMenu...
