### ISSUE TITLE
System Package Replacement List

### ISSUE THREAD

**Issue by Bad-Wolf-Plays** [feren-OS/feren-OS-Bug-Reporting#18]
All base Mint packages: Cinnamon et al..
systemd (all)
iniit (all) 
libpam-systemd
libsystemd (all) 
MDM (all) {Did not reinstall. Replaced with LightDM. Personal preference.} 

I explained to Feren how to accomplish it. But, if more info needed, let me know. 

"Sometimes you must destroy, in order to create."

**Comment by feren** [comment]
Because of Bad Wolf is back on Windows 10 LTSB, and feren OS 2017.08 is back to a fresh Mint base, that BWP found to just work mostly, this issue is now invalid and will be closed.
