### ISSUE TITLE
Live USB of FerenOS 2017.01 x64 ask to boot FerenOS 2016.2

### ISSUE THREAD

**Issue by reubrester** [feren-OS/feren-OS-Bug-Reporting#19]
Hello,

I just downloaded the latest version of FerenOS from SourceForge and put it on an USB drive.  I boot to the drive and it ask me to boot to 2016.2 instead of 2017.01 (which is what I downloaded).  Is it going to boot into 2017.01 or 2016.2?

Thanks,
Reubrester

**Comment by feren** [comment]
That'll be fixed next week.

**Comment by reubrester** [comment]
Thank you.

**Comment by feren** [comment]
About to be fixed in a few minutes...
