### ISSUE TITLE
Live OS eventually fails to run any applications

### ISSUE THREAD

**Issue by joshuah345** [feren-OS/feren-OS-Bug-Reporting#20]
vivialdi crashes and all applications can be used until you close them. if you try opening anything, it will not run

**Comment by feren** [comment]
Odd, don't see that issue here...
Did you check your ISO MD5Sum and Sha256Sums?

**Comment by joshuah345** [comment]
Yes they are correct. This happens after you use the live os for more than around 15 minutes

**Comment by feren** [comment]
Does the problem also happen in Linux Mint 18.1 Cinnamon Edition?
