### ISSUE TITLE
Cinnamon does not start

### ISSUE THREAD

**Issue by joshuah345** [feren-OS/feren-OS-Bug-Reporting#21]
When booting from live CD all I get is a black screen with the mouse.
I let it sit for 15 min and nothing changes

**Comment by joshuah345** [comment]
checking the integrity of the medium told me there were errors with 12 files but remaking the flash drive gave me the same thing

**Comment by feren** [comment]
Hmm, not sure then...
Does hitting CTRL+ALT+F2 on the black screen, then logging in a 'mint' with Password just being pressing ENTER, then, at the prompt, typing 'killall --user mint' and then letting it log in again change anything?

**Comment by joshuah345** [comment]
After doing the commands and a graphical login I'm back at the black screen

**Comment by joshuah345** [comment]
Wait I had to do it a second time
