### ISSUE TITLE
Packaging problem

### ISSUE THREAD

**Issue by olsonjp84** [feren-OS/feren-OS-Bug-Reporting#22]
I cant install ClamAV because there is a packaging problem on your side:

N: Ignoring file '50unattended-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension

**Comment by feren** [comment]
sudo rm -rf /etc/apt/apt.conf.d/50unattended-upgrades.ucf-dist

PS: It isn't actually a problem, just an upstream bug that APT lets you know about
