### ISSUE TITLE
Record Desktop not wokring

### ISSUE THREAD

**Issue by kp2401075** [feren-OS/feren-OS-Bug-Reporting#24]
Screenshot  & record desktop applet is taking screenshots properly how ever when recording the desktop 

it is not saving recorded videos.

**Comment by feren** [comment]
I've inspected the source code of this, and it turns out it needs a package called `ffmpeg`

To install it, run `sudo apt install ffmpeg -y`
sudo - Tells the computer to run the command as the Superuser (the God of the OS Installation)
-y - Tells APT to assume YES to all questions it may ask

**Comment by feren** [comment]
Fixed in the latest Update.
