### ISSUE TITLE
UEFI boot

### ISSUE THREAD

**Issue by kp2401075** [feren-OS/feren-OS-Bug-Reporting#25]
There is no Proper instructions given to make iso to UEFI bootable

<rant>
i have wasted whole day trying different stuff, I really like Feren Project and wanted to install it on my Daily Laptop with UEFI but wasn't able to 
</rant>

**Comment by kp2401075** [comment]
Please add Instruction to use UnetBootin On the Download page

**Comment by feren** [comment]
@kp2401075 Does Startup Disk Creator give you the UEFI you need for the ISO?

**Comment by kp2401075** [comment]
@feren no I have tried all the ways to create bootable usb Gnome-Disks, Startup DIsk creator, DD 

none of them worked 

I was able to get it working with Unetbootin.
