### ISSUE TITLE
[FEREN GTK] Default feren OS Theme needs upgrading to make sure the next Major Update doesn't break it

### ISSUE THREAD

**Issue by feren** [feren-OS/feren-OS-Bug-Reporting#28]
feren OS's Default Theme DOES NOT support Ubuntu 18.04, right now, and needs upgrading, as to prevent the GTK theme from breaking in feren OS 2018 Releases...

**Comment by luiz8719** [comment]
nobody knows anything about it?

**Comment by feren** [comment]
Basically, I checked it once in Ubuntu 17.04, and to say it was broken there would be correct, to the bit where it was just background and text, no other theming by the theme, which is unusable.

**Comment by feren** [comment]
UPDATE: Looks like I'll have to check to make sure an Arc base compatible with 18.04 by the time it comes (I'll work on the GTK Theme Upgrade when I know Ubuntu 18.04's sat on a GTK version to use) also has a working restore button for apps like Chrome.

**Comment by feren** [comment]
Fixed in Earlybird Repo, and soon to appear in Stable once 18.04-base-upgrade is available to Feren OS Users, post-testing.
