### ISSUE TITLE
[DPKG] Locked when trying to remove system package

### ISSUE THREAD

**Issue by luiz8719** [feren-OS/feren-OS-Bug-Reporting#30]
I entered the terminal and typed the "sudo apt-get remove gnome-keyring" command, but the terminal returned the following ## **"E: Unable to get lock / var / lib / dpkg / lock - open (11: Resource temporarily unavailable)"
"E: Could not get exclusive access to the admin directory (/ var / lib / dpkg /), another process is using it?"**
how to solve this personal?

**Comment by feren** [comment]
Wait for a little bit, it's either Mint Update Refreshing, or Unattended Upgrades updating packages in the background, so wait until DPKG becomes free to lock again, and then you'll be able to uninstall 'gnome-keyring'.
