### ISSUE TITLE
Automatic Digital Desktop clock

### ISSUE THREAD

**Issue by jantoonen** [feren-OS/feren-OS-Bug-Reporting#31]
I seem not to be able to quit the default desktop clock or change the format into 24 hour notation, what do I do wrong?

**Comment by feren** [comment]
1. Press <kbd>Alt</kbd>+<kbd>F2</kbd>
2. Type in <kbd>killall conky</kbd>
3. Go into Home
4. Press <kbd>Ctrl</kbd>+<kbd>H</kbd>to show Hidden Files
5. Display 'conky.rc'
6. Change `${voffset -8}${offset 23}${font Open Sans Light:pixelsize=60}${time %I:%M}${font Open Sans Light:pixelsize=14}${time %P}$font` to `${voffset -8}${offset 23}${font Open Sans Light:pixelsize=60}${time %H:%M}$font`
