### ISSUE TITLE
[Welcome Screen] Page Doesn't Load

### ISSUE THREAD

**Issue by monk10101** [feren-OS/feren-OS-Bug-Reporting#32]
I only get a white welcome screen.
I did change theme to win7 look a like(basic)
but even the feren default it's the same.
searched for a fix, but no luck so far. (worked fine at first boot in virtual machine)

the 2006.2 version works great, but I thought i'd give the new version a try.
every once in a while in the new version i only get black screen after login.
hope things get resolved.       thank you

**Comment by feren** [comment]
What do you mean by "white screen"?

TIP: Screenshot can take Screenshots

**Comment by monk10101** [comment]
ok I got a screenshot from my windows program because the screen grabber in feren only showed a 
black screenshot.   hope this helps
I also ran some of the sugestions from this web page after install:
https://sites.google.com/site/easylinuxtipsproject/mint-cinnamon-first

**Comment by monk10101** [comment]
![snap_2017 09 11 09 09 23_002](https://user-images.githubusercontent.com/31822964/30279777-b880f960-96d3-11e7-8452-af4becc47ec5.jpg)

**Comment by feren** [comment]
Can you check /usr/share/feren-welcome to and take a screenshot of it?

**Comment by monk10101** [comment]
ok
![snap_2017 09 11 14 54 23_001](https://user-images.githubusercontent.com/31822964/30294095-8c4012cc-9701-11e7-8701-a9a3b58fd986.jpg)

**Comment by feren** [comment]
...what happens if you double-click on index.html and hit Display, is it blank there too?

**Comment by monk10101** [comment]
no, i can open these in vivaldi but some links  don't  work says no internet connection for chat and some downloads. i can get downloads from software center but i don't have a link for gitter chat for feren.
whats the name of the backup program and game pack?

**Comment by feren** [comment]
@monk10101 Don't worry about the errors shown there, they're just there as placeholders to hide when not needed.
Try running 'feren-welcome' in Terminal, and paste the output here...

**Comment by monk10101** [comment]
ok i get back in soon after i try that. thanks

**Comment by monk10101** [comment]
ok this is what i get
![snap_2017 09 12 11 03 30_001](https://user-images.githubusercontent.com/31822964/30336317-729fb972-97aa-11e7-8511-40129593410c.jpg)

**Comment by feren** [comment]
Hmm... I have no idea, what's your locale?

**Comment by monk10101** [comment]
loacation? usa chicago

**Comment by monk10101** [comment]
does this require the program mono to run? was uninstalled from the sugestions from the link above
that i posted

**Comment by feren** [comment]
I don't think so, let me check...

**Comment by monk10101** [comment]
this is my locale settings
locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

the default screen capture won't work. tried another called "shutter" but that also only grabs a black blank screen.  I can live without the welcome screen, can you give me the gitter chat link for feren?

**Comment by feren** [comment]
https://gitter.im/feren-Community/General-Discussion
