### ISSUE TITLE
[HARDWARE] System too slow, even on other Distributions when there's a big workload

### ISSUE THREAD

**Issue by luiz8719** [feren-OS/feren-OS-Bug-Reporting#33]
hello, I wanted to know when there are several applications open the system ends up getting a little slow and also when app spends a minimized time in the dock when we open it again it takes or it opens but its screen gets locked the rest of the system works more that app does not work.

I realized this in other linux distro, making it clear that my computer is not a PC with weak hardware.

**Comment by feren** [comment]
...I'm sure that's an upstream bug, so, for now, is there any other point to this issue?

**Comment by luiz8719** [comment]
no, I just want to know what this is and how to solve it because I also noticed it in other distro like elementary, for example.

any response to this?

**Comment by feren** [comment]
:thinking: 
I'm personally not sure, but what I could suggest is switching the Vivaldi browser over to Firefox in Web Browser Manager, to reduce Resource Usage, other than that, maybe check out Solus, see if anything's better there.

**Comment by luiz8719** [comment]
already excludes Vivaldi and also erased the solus, but I do not think they consume that much appeal.

vivaldi is lightweight browser, right?

**Comment by feren** [comment]
@luiz8719 Hmm, not really, it's based on the daddy of the RAM Eater Chrome, after all.

**Comment by luiz8719** [comment]
did not know that it was based on chrome, but in relation to those crashes no information on this?

**Comment by feren** [comment]
Don't really get what the crashes are...

**Comment by luiz8719** [comment]
I wanted to know when there are several applications open the system ends up getting a little slow and also when app spends a minimized time in the dock when we open it again it takes or it opens but its screen gets locked the rest of the system works more that app does not work.

this is the accident that happens when I end up running several applications.

**Comment by feren** [comment]
@luiz8719 It's probably the system then, if it affects other distros, too. feren OS isn't a Light OS, after all.

Suggestions:
1. Get a Windows Laptop known to work with Linux (Not AMD, those have issues from what I've seen nowadays)
2. Get a Linux Laptop (there's a growing number of 'em)

**Comment by luiz8719** [comment]
I have a PC and not a notebook, consequently the parts of my PC have been replaced reciprocally so all the OSs I have installed so far have been distros linux, but the feren without doubt is the best I have ever used.

**Comment by luiz8719** [comment]
Luckily there have not been more crashes like the ones I mentioned here, I do not know what happened might have been an update, but it's just my curiosity to know why this happens, if you do not have the answer to that, there's no problem at all.
