### ISSUE TITLE
Window redraw lag when dragging windows

### ISSUE THREAD

**Issue by JoMas971** [feren-OS/feren-OS-Bug-Reporting#36]
Hello,
We have the same issue explained in this cinnamon thread : 
https://github.com/linuxmint/Cinnamon/issues/2465

Since FerenOS is based on a fork of Cinnamon, i wonder if there is a planned to fix it (or at least explain why the bug occurs) directly by FerenOS community or if you'll wait for a fix from Cinnamon DEVs instead.

Thanks.

**Comment by feren** [comment]
I'll let them fix it, personally.
