### ISSUE TITLE
BUG: Update made apps on panel go away

### ISSUE THREAD

**Issue by zaivala** [feren-OS/feren-OS-Bug-Reporting#38]
For whatever reason, a recent update made my panel apps go away, including apps currently open. When I minimize anything, I might as well have closed it. As I can now no longer do my work in ferenOS, I have to install something else on my machine to do so (I have a free partition to do this, don't have to wipe feren).

Also, if it has not been reported earlier, Kodi no longer loads on feren. It opens and flashes closed in less than a second.

**Comment by feren** [comment]
Right-click on the Panel, Add Applets to Panel, re-add Icing Task Manager. I'll look into it later when at my laptop.

**Comment by feren** [comment]
...anyways, thanks for reporting it, otherwise I wouldn't know this happened.

**Comment by feren** [comment]
@zaivala What were you doing up to the ppint when the applets disappeared?

**Comment by zaivala** [comment]
I don't do anything fancy. I use PlanMaker to keep my budget, read my email and pay bills (some on Firefox, some on Vivaldi, as some websites seem to only run on Chromium), and run a Mullvad VPN. When I watch TV, thanks to Kodi not working (that has gone on for months now, at first it just blinked out once or twice and then ran, then later just blinked out every time), I'm not using it for that. I'm not a gamer, and not a programmer or tweaker, just someone who uses Linux the way he would have been using Windoze except more safely.

**Comment by feren** [comment]
@zaivala Does that above step work?

**Comment by zaivala** [comment]
Don't know. I had a lot of work to do, compounded by the fact that I had to install another OS to get that work done. I may check on it later this weekend.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by zaivala** [comment]
OK, I tried that. It took so long to ad the Applets menu I thought it didn't work, but eventually a list came up. I looked for Icing Task Manager. It was not currently in use, so I added it. Nothing changed. Nothing. Had to open my browser again -- I'm running two instances of Firefox right now but cannot get to the other one.

**Comment by feren** [comment]
Weird, can you Screenshot it?

**Comment by zaivala** [comment]
![screenshot from 2017-10-18 17-38-58](https://user-images.githubusercontent.com/28702896/31744115-8b1dfe4e-b42b-11e7-992c-28b6755d66b8.png)

Note that there are none of my selected apps in the Launcher (next to the folded bird icon), and no tab for Firefox. If I minimize Firefox, I can't un-minimize it.

**Comment by feren** [comment]
@zaivala Can you screenshot System Settings > Applets, namely the IcingTaskManager entry in there?

**Comment by zaivala** [comment]
Not interested in doing any more work with Feren. Not enough time to troubleshoot, I just want something that works.

**Comment by feren** [comment]
k.
