### ISSUE TITLE
No login after fresh install with HOME crypted...

### ISSUE THREAD

**Issue by stragic-it** [feren-OS/feren-OS-Bug-Reporting#39]
Hi,
i installed FEREN OS yesterday (64bit, HOME crypted) on an SONY notebook. All went fine, but the first start is only going to the login screen. Password is correct but the login screen comes in an endless loop.

And NOW?

Bye
STRAGIC-IT

**Comment by stragic-it** [comment]
Hi there...
if I install FEREN OS without HOME crypted, all went fine, but with HOME crypted - always an endless loop at login screen.

Why?

LinuxMINT MATE works fine with this...

**Comment by feren** [comment]
I'm honestly not sure, unless it has something to do with feren OS's user creation folder permissions being "Read and Write for user, Nothing for Other Users"...

**Comment by stragic-it** [comment]
Ok... and how can I patch it?

**Comment by feren** [comment]
Hmm, this is weird, looks like it's already at 755 by default... :thinking:
