### ISSUE TITLE
Themer not installing new things

### ISSUE THREAD

**Issue by fenrisTL** [feren-OS/feren-OS-Bug-Reporting#41]
Hiya,

I have this small problem with installing new themes in Themer. On my laptop all works fine, but not on the main PC. When I click on theme it will ask me for password and start downloading (yes I am connected) and then this pop-up window:
![screenshot from 2017-11-07 01-56-48](https://user-images.githubusercontent.com/33439138/32473479-981301ec-c35f-11e7-9adc-407577b2d814.png)

Thanks for any help. 
--
Tom

**Comment by feren** [comment]
Try running 'sudo apt install numix-themer' in a Terminal window

**Comment by veggiedev** [comment]
I have the exact same problem. Trying to install macos sierra theme and gives error. Any new theme is giving error to install

**Comment by fenrisTL** [comment]
Hiya and thanks for replay,
OK I have tried it and it won't work. I did even 'sudo apt search numix-themer' and it is not there. 
using synaptic package manger does not show anything either. Later I removed Themer and was trying to install again but no luck. Now I don't have Themer...
I did not touch repos so they are as they came with system. 
Thanks

**Comment by fenrisTL** [comment]
I think I've found solution....
All I did was switching to Unstable Packages (in Software Sources) and then in Synaptics Package Manager I put "feren" in search field, then installed Themer and all the themes, icons etc.

Now all works fine and I can customized it as I want :)

**Comment by veggiedev** [comment]
was it in the repo in synaptics after uninstalling it? deleted it before and couldnt find it. Had to do a complete reinstall of the system...

**Comment by veggiedev** [comment]
In case it helps trace the issue, the live iso does allow you to download and install new themes in the Themer

**Comment by fenrisTL** [comment]
After I uninstalled the Themer I could not find the packages in the Stable repo. That is why I switched to Unstable and it allowed me to install them again.
