### ISSUE TITLE
[Out Of Date Packages Installed] the theme updates break the cinnamon desk top(asks to restart in a loop) reverts to fallback mode

### ISSUE THREAD

**Issue by monk10101** [feren-OS/feren-OS-Bug-Reporting#44]
running feren with these updates hidden till fixed.

**Comment by feren** [comment]
@monk10101 Try the latest update to 'feren-themer', hopefully that'll fix it.

**Comment by feren** [comment]
...if not, go in Utilities or Accessories > Terminal, and run 'sudo /usr/bin/feren-fix-system-settings-24122017' and see if there's any error there.

**Comment by monk10101** [comment]
there were 2 updates:  1.)windows7-themer and 2.) feren-themer .
when these were installed and rebooted, the cinnamon desktop crashed and asked to be restarted.
clicked yes and it keeps crashing each time I click yes. my theme is currently windows7  with the old themer. I'am running feren (18.3) in a virtual machine so i can roll back if needed.
I will try your sugestions soon. should I try one or both updates?

**Comment by monk10101** [comment]
tried to install feren-themer only and got this error (see screenshot)
![error installing feren-themer-only](https://user-images.githubusercontent.com/31822964/34391439-32b2f9be-eb0b-11e7-96ab-bf7d6834b5b4.jpg)
then ran sudo /usr/bin/feren-fix-system-settings-24122017 said not found.

i'am trying windows7-themer update this time to see if that crashes cinnamon.

**Comment by monk10101** [comment]
windows7-themer installed O.K
then i installed feren-themer then rebooted and got the cinnamon crash.
![error after install feren-themer](https://user-images.githubusercontent.com/31822964/34393054-6f0df7ec-eb15-11e7-8400-dc74ed2e75f3.jpg)

then I ran the  'sudo /usr/bin/feren-fix-system-settings-24122017' in terminal and got this:
![error after terminal entry](https://user-images.githubusercontent.com/31822964/34393087-a4162072-eb15-11e7-9555-c276ca1fcb4f.jpg)

going back before I installed feren-themer. (rollback)

**Comment by monk10101** [comment]
looks like something needs to be updated.
let me know if you can solve this.  thanks

**Comment by feren** [comment]
Ok, assuming you got all the updates, run 'sudo apt update && sudo apt-get -f install -y && sudo apt upgrade -y' without the quotes in Terminal

**Comment by monk10101** [comment]
well it did fix cinnamon from crashing, but now at of system things don't run.
right click on desktop and choose desktop settings (nothing)
try to get to configure applets (nothing)
try to run theamer (nothing)

and it still shows old windows7 theme.
I think i'll just go back and keep feren-themer update hidden, there were some things that did not look right after the command usd above.
i also tried:  sudo apt-get update
                   sudo apt-get upgrade
                   sudo apt-get dist-upgrade
none worked

**Comment by monk10101** [comment]
re-ran the sudo /usr/bin/feren-fix-system-settings-24122017 command and that fixed it.
but it still show old theme.
trying to figure how to change it.
tried to download the windows7 theme (from theme store) but it says archive type not supported.
(new themer program now runs)
any sugestions?

**Comment by monk10101** [comment]
I think I got it now.
(it was a theme file not a archive file)
still looks a lot like the old theme thou.
thanks doctor feren.    :)

**Comment by feren** [comment]
So, fixed now?

**Comment by monk10101** [comment]
yes looks to be fixed. thanks again
