### ISSUE TITLE
Installed Feren Os from latest iso

### ISSUE THREAD

**Issue by Ken-2018** [feren-OS/feren-OS-Bug-Reporting#46]
I installed Feren Os on Dec 30th which was the latest ISO off sourceforge and after which it needed several updates.  I performed these multiple updates one after another but after performing these updates the package manager said something like after these updates hopefully everything was fixed or something like this. But it broke the start menu,  system settings and nothing program related would work or was linked everything appeared broken even running from command line would produce errors. In short the whole system was broken including system setting, themes applets as nothing would function after the updates.

**Comment by feren** [comment]
Sure you got the right ISO? There is no update available for feren OS January Snapshot yet? (Is Themes on the Desktop before updating, or is it Themer?)

**Comment by Ken-2018** [comment]
It was themer on desktop but did mention it was uninstalling themer for themes but the update failed miserably and I was left with an unoperational system.  I see the new iso works and the only updates available are firefox and a new kernel. I will try the new iso later.


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: The feren OS Dev <notifications@github.com> Date: 1/2/18  8:40 AM  (GMT-06:00) To: feren-OS/feren-OS-Bug-Reporting <feren-OS-Bug-Reporting@noreply.github.com> Cc: Ken-2018 <dragonslair2005@gmail.com>, Author <author@noreply.github.com> Subject: Re: [feren-OS/feren-OS-Bug-Reporting] Installed Feren Os from latest
  iso (#46) 
Sure you got the right ISO? There is no update available for feren OS January Snapshot yet? (Is Themes on the Desktop before updating, or is it Themer?)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/feren-OS/feren-OS-Bug-Reporting","title":"feren-OS/feren-OS-Bug-Reporting","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/feren-OS/feren-OS-Bug-Reporting"}},"updates":{"snippets":[{"icon":"PERSON","message":"@feren in #46: Sure you got the right ISO? There is no update available for feren OS January Snapshot yet? (Is Themes on the Desktop before updating, or is it Themer?)"}],"action":{"name":"View Issue","url":"https://github.com/feren-OS/feren-OS-Bug-Reporting/issues/46#issuecomment-354779998"}}}

**Comment by feren** [comment]
@Ken-2018 Oh, your ISO is outdated then, get the latest one.
