### ISSUE TITLE
Variety wallpaper changer

### ISSUE THREAD

**Issue by Ken-2018** [feren-OS/feren-OS-Bug-Reporting#48]
I installed the latest Feren Os iso and I did all the updates including the new kernel offered etc. Next I installed variety wallpaper changer however when I launched the program it disappeared and when I tried to bring it back nothing shows up.  I rebooted and on reboot it shows the Variety wallpaper sign in or participate anonymously page but it's certainly frozen so I can't select anything or get the sign in page off the screen unless I force it to quit. Any suggestion besides uninstalling it because I did this several times.

**Comment by Ken-2018** [comment]
The Variety wallpaper changer would load but fail to let me pick the buttons to participate in syncing the wallpaper at VRTY.org anonymously or sign up. The window was not functional as I moved the window around the screen the buttons are not working to proceed to the next screen in Variety and the program would hang forcing me to close it. So I reinstalled the the whole FEREN OS and it's working now.

**Comment by Ken-2018** [comment]
Nope it's back, this window won't close.
![screenshot from 2018-01-10 17-04-11](https://user-images.githubusercontent.com/35033068/34800392-256a9176-f629-11e7-8e64-733b9af44a93.png)

**Comment by feren** [comment]
In a Terminal, try this code, and then report back with the output (if any):
```
killall variety
variety
```

**Comment by Ken-2018** [comment]
It pops right back to this window.

![](https://user-images.githubusercontent.com/35033068/34800392-256a9176-f629-11e7-8e64-733b9af44a93.png)

**Comment by feren** [comment]
...any output in Terminal?

**Comment by Ken-2018** [comment]
Yes I get errors I will post shortly just a bunch of random errors. But I think this may be a variety problem connecting to vrty.com some where on the back end.

**Comment by feren** [comment]
Yeah, could be that Variety's VRTY servers are permanently closed down...
