### ISSUE TITLE
Help !!! I can not modify Software Sources.

### ISSUE THREAD

**Issue by pegassus55** [feren-OS/feren-OS-Bug-Reporting#49]
In the middle of last year I found Feren OS and decided to try it, honestly I was delighted with the performance, ease of use and costumization of the distro. Recently for some reason that I do not remember at this time I wanted to modify Software Sources but strangely I can not get it to run. This happened for more than 30 days however I have not had any problems with the updates which the Software Manager notifies and installs correctly. Despite having no visible problems at the moment, I am a bit worried about not being able to modify the Software Origins. Thanks in advance for any information that could help me solve the problem.

**Comment by feren** [comment]
Go into a Terminal, and run `sudo mintsources` and then copy n paste the output here

**Comment by pegassus55** [comment]
Thank you very much for supporting me, when executing the suggested command the result is the following:

Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1600, in <module>
    Application().run()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 748, in __init__
    if self.config["general"]["use_ppas"] == "false":
KeyError: 'general'


Hopefully it is possible to solve the problem without having to reformat the hard drive. Thanks in advance.

**Comment by feren** [comment]
Can you try running in Terminal `sudo apt install --reinstall mintsources` and see if that helps?

**Comment by pegassus55** [comment]
Hello good day. unfortunately when trying to reinstall mintsources the result was that it was not possible to download them.

jose@jose-LIBERO ~ $ sudo apt install --reinstall mintsources
[sudo] password for jose: 
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No es posible reinstalar el paquete mintsources, no se pudo descargar.
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.

Maybe there is some way to download and install it differently? Thanks!

**Comment by pegassus55** [comment]
Update of the problem: based on the previously received suggestion, I decided to search and download the mintsources package and obtained it from http://packages.linuxmint.com//pool/upstream/m/mintsources/mintsources_1.7.2_all.deb I proceeded to installed it which was done without any inconvenience and the problem was completely solved since I was able to run mintsources without any other incident. Thanks for the help that was given me and I proceed to close the issue.
![captura de pantalla de 2018-01-27 09-54-49](https://user-images.githubusercontent.com/16092842/35474221-80283862-0348-11e8-8013-57d2ef41656a.png)
