### ISSUE TITLE
update feren theme 2017.02.0.01 causing no password entry at login

### ISSUE THREAD

**Issue by monk10101** [feren-OS/feren-OS-Bug-Reporting#50]
can only login as guest. password entry is white and shows no curser, not allowing entry of password.
for now this update is blocked on my virtual machine.   hope this helps others.

**Comment by feren** [comment]
I'll try to revert the theme back in that case to when it wasn't white...
PS: You can still type the password in, even though it's White

**Comment by monk10101** [comment]
for me there was no way of entering a password (did this twice-rollback twice)
maybe a virtualbox bug?

**Comment by feren** [comment]
The theme has been rolled back to a copy without this issue in an update, closing the issue now...
