### ISSUE TITLE
Install & Login

### ISSUE THREAD

**Issue by skyofwing** [feren-OS/feren-OS-Bug-Reporting#51]
What is the username and password of the LiveCD? After I make the ISO to the USB, I booted the computer into the LiveCD login screen. . . All tried passwords have been tried.I can't get in and install.

**Comment by feren** [comment]
Username: mint (otherwise it's the same as the text on the top-left of the login screen)
Password: None

**Comment by skyofwing** [comment]
ok,i'll try .think you.
