### ISSUE TITLE
Startup Slow / XFCE4 won't load correctly 

### ISSUE THREAD

**Issue by xulefuhib** [feren-OS/feren-OS-Bug-Reporting#7]
Hello, i have a problems when i install XFCE4 on the feren OS new development build where i can't load xfce when i try to load it i only get a black screen and i see my mouse that's it, the startup issue I'm facing is that its going to slow when i don't think it should be i have an SSD device and when i run something like Manjaro it loads about 2 times as fast i don't know if you can do anything about that but that's fine if you can't :) oh and BTW i think its a great OS i really like the themes / wallpapers also.

**Comment by feren** [comment]
@xulefuhib Can you try to see if there's a similar problem with Linux Mint 18.1?
If there isn't, you may be able to work around this by using the upcoming Linux Mint to feren OS tool (Coming Soon) Update that'll let you choose what you want to add to Mint that's in feren OS...

**Comment by feren** [comment]
@xulefuhib Personally, I don't check XFCE and other non-Cinnamon DEs that much, so it slips into the OS easily, I'll try to fix this in 2017.1

**Comment by xulefuhib** [comment]
Oh great :) thanks so much for fixing that issue actually you know whats funny i tried out linux mint for my daily driver yesterday just for fun and it was pretty slow to so i think its just a linux mint thing it just takes about 45 seconds to load rather than usually a 12 second boot up on a different distro its probably because its loading more services and stuff but its fine as i said if you can't fix it only thing that i want fixed is the xfce and other desktop environments to go along with feren and i also have a great suggestion sense feren os is very customization to themes and everything can you add like a SDDM login screen changer or themer for what the login screen looks like.

**Comment by feren** [comment]
There's already MDM's Login Screen thing where you can change skins, and right now, there isn't a theme for every OS option for MDM yet...

**Comment by xulefuhib** [comment]
ah i see, alrighty :) thanks for the fixes btw when do you plan releasing the next build ?

**Comment by feren** [comment]
@xulefuhib The next build will be Stable, more to come in a few days...

**Comment by feren** [comment]
@xulefuhib I might've found a fix for XFCE:
This file is preventing XFCE from working: /etc/X11/Xsession.d/00upstart

The Fix: Either remove the file, or find the package relating to this file, and remove it if it isn't critical
