### ISSUE TITLE
Links from Start menu don´t work

### ISSUE THREAD

**Issue by scomnetgate** [feren-OS/feren-OS-Bug-Reporting#9]
I have changed the default language to Spanish and I have updated the system and load windows 7 aero theme. The start menu links like “Images”, “Videos”, “Music” doesn’t change from english language and the links don´t work. I am using feren OS 2017.0 RC

**Comment by scomnetgate** [comment]
I am using feren OS 2017.0 RC

**Comment by NikoKrause** [comment]
@scomnetgate
Could you create a ZIP file of the applet you are using and drag&drop it here? I'd like to see the code.

Also which language does your computer is set to? Spanisch, Spain?

A Screenshot of your home folder and one from the menu would be helpful as well.

**Comment by feren** [comment]
@NikoKrause 
[CinnVIIStarkMenu@NikoKrause.tar.gz](https://github.com/feren-OS/feren-OS-Bug-Reporting/files/947973/CinnVIIStarkMenu.NikoKrause.tar.gz)

**Comment by feren** [comment]
@scomnetgate NikoKrause is the developer of the Menu you see on the Windows Themes in feren OS, also known as 'CinnVIIStarkMenu'

**Comment by NikoKrause** [comment]
I need to see a screenshot of the home folder and from the menu.

**Comment by feren** [comment]
sr.po:7: warning: header field 'Language' missing in header
(Same error for "ku.po:7:)

Other than that, says it did it successfully

**Comment by feren** [comment]
@scomnetgate Try this in Terminal:
`cd /usr/share/cinnamon/applets/CinnVIIStarkMenu@NikoKrause && sudo apt install python-polib && cinnamon-json-makepot -i`

**Comment by scomnetgate** [comment]
I have make a default installation. The language set is Spanish.
![ferenos desktop](https://cloud.githubusercontent.com/assets/10704722/25297084/00776dd8-26ec-11e7-914f-2c58ace9720e.jpeg)
I have try what you ask and the result is:
![terminal](https://cloud.githubusercontent.com/assets/10704722/25297233/c5deeda8-26ec-11e7-8699-66e0cbe60702.jpeg)
I can correct the problem manually using CinnVIIStarkMenu configuration but every time I change the theme it change back...

**Comment by NikoKrause** [comment]
@scomnetgate
The problem was, that the applet wasn't translated at all.
The command that feren posted, should solve this problem.
You already did it. Your terminal output says: "Install complete for domain..."
After restarting Cinnamon, the applet should be translated and the links should work.
Does it?

**Comment by scomnetgate** [comment]
Yes it does ! The only thing y see is not translated is "All Apps" and "Back" in the start menu down side.

**Comment by NikoKrause** [comment]
They should be translated. I suspect, that you gave them custom names.
By default they are called "All Programs" and "Favorites". The Spanish translation is complete, so the default names are translated.
Therefore you must have changed it in the settings on your own.

**Comment by NikoKrause** [comment]
Or was it @feren, who changed it?

**Comment by scomnetgate** [comment]
I did't change anything...

**Comment by NikoKrause** [comment]
Try to change it to "All Programs" and "Favorites"

**Comment by scomnetgate** [comment]
If I change the text  everything works as it should and translates perfectly.

**Comment by NikoKrause** [comment]
Then it's feren, who changed it ;)

**Comment by scomnetgate** [comment]
I hope hope he do it right when makes the release image ;)

**Comment by scomnetgate** [comment]
By the way ... I'm impressed with the work you gays have done with this distribution. Very nice and beautiful job... Congratulations...

**Comment by NikoKrause** [comment]
Please read your last post again!

**Comment by feren** [comment]
@scomnetgate Is this fixed now?
